# Numpy Sorting

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [4]:
v

array([2, 1, 4, 3, 5])

In [5]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

# two dimension

In [11]:
a = np.random.normal(20,5, (3,3))

In [12]:
a

array([[22.83441216, 23.6014194 , 24.84111865],
       [20.60731465, 14.45050993, 15.28464156],
       [15.04297144, 23.21073011, 16.80281861]])

In [15]:
np.sort(a, axis = 1)

array([[22.83441216, 23.6014194 , 24.84111865],
       [14.45050993, 15.28464156, 20.60731465],
       [15.04297144, 16.80281861, 23.21073011]])

In [17]:
np.sort(a,axis=0)

array([[15.04297144, 14.45050993, 15.28464156],
       [20.60731465, 23.21073011, 16.80281861],
       [22.83441216, 23.6014194 , 24.84111865]])