# Numpy Splitting

In [1]:
import numpy
import  numpy as np

In [3]:
x = np.array([1,2,3,99,99,3,2,1])

N indexe karşılık n+1 bölüm ayırılır

In [ ]:
np.split(x, [3,5])

In [5]:
a,b,c= np.split(x, [3,5])

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([99, 99])

In [8]:
c

array([3, 2, 1])

# Two Dimension

In [9]:
m  =np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [11]:
top, down = np.vsplit(m,[2])

In [12]:
top

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
down

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [16]:
left, right = np.vsplit(m,[2])

In [17]:
left

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
right

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])