# Create Numpy Array

In [10]:
import numpy as np

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
a = np.array([1,2,3,4,5])

In [13]:
type(a)

numpy.ndarray

In [14]:
np.array([3,14,2,13,3.14])

array([ 3.  , 14.  ,  2.  , 13.  ,  3.14])

# create an array from scratch

In [1]:
import numpy as np

NameError: name 'np' is not defined

In [ ]:
np.zeros(10,dtype=int)
np.ones((3,5),dtype=int)

In [15]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [4]:
np.arange(0,31, 3)

In [ ]:
np.linspace(0,1,10)

In [20]:
np.random.normal(10, 4,(3,4))

array([[ 8.56223617,  6.56234929, 10.28171245, 10.64179592],
       [ 9.48309109,  6.99689979, 12.39544772, 13.72878577],
       [ 4.95692998,  4.97287202, 10.06920937, 16.31807714]])

In [21]:
np.random.randint(0,10, (3,3))

array([[9, 1, 1],
       [9, 8, 6],
       [5, 0, 3]])