In [1]:
import numpy as np
a = np.random.randint(10,size=10)
a

array([6, 1, 5, 5, 6, 3, 6, 9, 4, 2])

In [2]:
a[0]

6

In [3]:
a[-1]

2

In [4]:
a[0] = 100

In [5]:
a

array([100,   1,   5,   5,   6,   3,   6,   9,   4,   2])

In [6]:
m = np.random.randint(10,size=(3,5))
m

array([[8, 2, 1, 3, 7],
       [2, 5, 8, 3, 2],
       [5, 9, 1, 0, 0]])

In [7]:
m[0,0]

8

In [9]:
m[1,1]

5

In [10]:
m[1,1] = 99

In [11]:
m

array([[ 8,  2,  1,  3,  7],
       [ 2, 99,  8,  3,  2],
       [ 5,  9,  1,  0,  0]])