In [5]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
v[1]

3

In [7]:
v[3]

9

In [8]:
v[5]

15

In [12]:
get_bring = [1,3,9]

In [13]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
v[get_bring]

array([ 3,  9, 27])

In [15]:
# two dimension fancy

In [16]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
row = np.array([0,1])
column = np.array([1,2])

In [18]:
m[row,column]

array([1, 5])

In [19]:
#fancy index with simple index

In [20]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
m[0,[1,2]]

array([1, 2])

In [22]:
#fancy with slice

In [23]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])