In [1]:
import numpy as np

In [2]:
a = np.arange (20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[2::2]

array([22, 24, 26, 28])

In [9]:
a[0::3]

array([20, 23, 26, 29])

In [10]:
#Two dimension slice operations

In [13]:
m = np.random.randint(10,size=(5,5))
m

array([[8, 4, 6, 3, 3],
       [9, 2, 7, 0, 5],
       [9, 1, 8, 8, 4],
       [2, 5, 4, 8, 6],
       [4, 9, 9, 9, 2]])

In [14]:
m[:,0]

array([8, 9, 9, 2, 4])

In [15]:
m[:,1]

array([4, 2, 1, 5, 9])

In [17]:
m[3,:]

array([2, 5, 4, 8, 6])

In [18]:
m[0]

array([8, 4, 6, 3, 3])

In [19]:
m[1,:]

array([9, 2, 7, 0, 5])

In [20]:
m[0:2,0:3]

array([[8, 4, 6],
       [9, 2, 7]])

In [22]:
m[::,:2]

array([[8, 4],
       [9, 2],
       [9, 1],
       [2, 5],
       [4, 9]])

In [23]:
m[1:3,0:2]

array([[9, 2],
       [9, 1]])

In [24]:
m

array([[8, 4, 6, 3, 3],
       [9, 2, 7, 0, 5],
       [9, 1, 8, 8, 4],
       [2, 5, 4, 8, 6],
       [4, 9, 9, 9, 2]])