In [2]:
import numpy as np
a = np.random.randint(10,size=(5,5))
a

array([[6, 7, 4, 0, 8],
       [1, 4, 5, 7, 8],
       [3, 9, 2, 9, 3],
       [7, 5, 2, 6, 2],
       [9, 7, 6, 8, 5]])

In [4]:
subset_a = a[0:3,0:2]
subset_a

array([[6, 7],
       [1, 4],
       [3, 9]])

In [6]:
subset_a[0,0] = 999999
subset_a[1,1] = 88888
subset_a

array([[999999,      7],
       [     1,  88888],
       [     3,      9]])

In [7]:
m = np.random.randint(10,size=(5,5))
m

array([[5, 0, 2, 2, 2],
       [3, 4, 5, 5, 0],
       [1, 1, 2, 7, 8],
       [0, 0, 1, 5, 9],
       [1, 7, 7, 2, 7]])

In [14]:
subset_b = m[0:3,0:2].copy()
subset_b

array([[5, 0],
       [3, 4],
       [1, 1]])

In [16]:
subset_b[0:0] = 999999
subset_b

array([[5, 0],
       [3, 4],
       [1, 1]])

In [10]:
m

array([[5, 0, 2, 2, 2],
       [3, 4, 5, 5, 0],
       [1, 1, 2, 7, 8],
       [0, 0, 1, 5, 9],
       [1, 7, 7, 2, 7]])