# Numpy Concatenation

In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6,])

In [5]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
z = np.array([7,8,9])

In [8]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## two dimension

In [9]:
a  =np.array([[1,2,3], [5,6,7,]])

In [11]:
np.concatenate([a,a])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [12]:
np.concatenate([a,a],axis=1)


array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])