In [9]:
import numpy as np
v = np.array([1,2,3,4,5,])
v

array([1, 2, 3, 4, 5])

In [2]:
v - 1

array([0, 1, 2, 3, 4])

In [3]:
v * 4

array([ 4,  8, 12, 16, 20])

In [5]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [6]:
np.subtract(v,1)  #  = v -1

array([0, 1, 2, 3, 4])

In [7]:
np.add(v,1)  # = v + 1

array([2, 3, 4, 5, 6])

In [8]:
np.multiply(v,4)  # v * 4

array([ 4,  8, 12, 16, 20])

In [10]:
np.divide(v,3)   #  = v / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [11]:
np.power(v,3)  # v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
np.mod(v,2)  # = v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.absolute(np.array([-3]))

array([3])

In [15]:
np.sin(360)

0.9589157234143065

In [16]:
np.cos(180)

-0.5984600690578581

In [17]:
v = np.array([1,2,3])

In [18]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [19]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [20]:
?np