In [1]:
import numpy as np

In [7]:
a = np.array([[5,1],[1,3]])
b= np.array([12,10])

In [3]:
a

array([[5, 1],
       [1, 3]])

In [4]:
b

array([12, 10])

In [5]:
x = np.linalg.solve(a,b)

In [6]:
x

array([1.85714286, 2.71428571])