# 1-Find the sum of all elements in a numpy array.

In [2]:
import numpy as np

In [6]:
m = np.array([1,2,3,4,5,6])
m

array([1, 2, 3, 4, 5, 6])

In [7]:
np.sum(m)

21

# 2-Find the sum of squares of all elements in a numpy array.

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [12]:
square_a = a ** 2

In [13]:
np.sum(square_a)

91

# 3-Find the avarage of all elements in a numpy array.

In [14]:
np.average(a)

3.5

# 4-Multiply two numpy arrays.

In [18]:
a = np.array([1,2,3,4,5,6])
m = np.array([1,2,3,4,5,6])
np.multiply(a,m)

array([ 1,  4,  9, 16, 25, 36])

# 5-Find the standard deviation of the elements in a numpy array.

In [19]:
m = np.array([1,2,3,4,5,6])
np.std(m)

1.707825127659933

# 6-Find the variance of the elements in a numpy array.

In [20]:
m = np.array([1,2,3,4,5,6])
np.var(m)

2.9166666666666665

# 7-Find the smallest and largest values of the elements in a numpy array.

In [21]:
m = np.array([1,2,3,4,5,6])

np.min(m)

1

In [22]:
np.max(m)

6

# 8-Reverse elements in a numpy array.

In [23]:
m = np.array([1,2,3,4,5,6])
np.flip(m)

array([6, 5, 4, 3, 2, 1])

# 9-Randomize a numpy array.

In [29]:
m = np.arange(10)
np.random.shuffle(m)

# 10-Create a two-dimensional numpy array and find the averages of the rows.

In [33]:
v = np.random.rand(4,4)
np.mean(v, axis=1)

array([0.17653553, 0.34739882, 0.425781  , 0.64676774])

# 11-Create a numpy array and calculate the Pearson correlation coefficient of all elements in that array with all other elements.

In [34]:
m = np.array([1,2,3,4,5,6])
np.corrcoef(m)

1.0